// Generated from config/sheet-config.toml by tools/build-sheet-config.py.
// Do not edit this file directly.
const RAW_SHEET_CONFIG = {
  "rollFormula": "2d6",
  "statToggle": false,
  "rollResults": {
    "failure": {
      "range": "6-",
      "label": "Complications..."
    },
    "partial": {
      "range": "7-9",
      "label": "Partial success"
    },
    "success": {
      "range": "10-11",
      "label": "Success!"
    },
    "critical": {
      "range": "12+",
      "label": "Critical Success!"
    }
  },
  "character": {
    "stats": {
      "might": "Might",
      "agility": "Agility",
      "wits": "Wits",
      "presence": "Presence",
      "force": "Force"
    },
    "attributesTop": {
      "species": {
        "type": "Text"
      },
      "look": {
        "type": "Text"
      },
      "vice": {
        "type": "Text"
      },
      "xp": {
        "type": "Xp",
        "max": 5
      }
    },
    "attributesLeft": {
      "condition1": {
        "type": "Text",
        "label": "Conditions"
      },
      "condition2": {
        "type": "Text",
        "label": ""
      },
      "condition3": {
        "type": "Text",
        "label": ""
      },
      "reflections": {
        "type": "ListMany",
        "label": "Reflections",
        "description": "Select up to three applicable questions.",
        "options": [
          "Did you make a meaningful connection with another character?",
          "Did you learn something important about the galaxy?",
          "Did you take a risk or face danger?",
          "Did you pursue your personal goals or beliefs?",
          "Did you create trouble, complications, or consequences?",
          "Did you reveal something significant about your character?"
        ]
      },
      "advancements": {
        "type": "ListMany",
        "label": "Advancements",
        "options": [
          "Increase an ability modifier by 1 (max +3)",
          "Increase an ability modifier by 1 (max +3)",
          "Increase an ability modifier by 1 (max +3)",
          "Choose an additional move from your playbook",
          "Choose an additional move from your playbook",
          "Create a custom move for your character",
          "Choose one optional move from another playbook"
        ]
      }
    },
    "equipmentTypes": {
      "gear": "Gear"
    },
    "moveTypes": {
      "basic": "Basic",
      "advanced": "Advanced"
    }
  },
  "npc": {
    "stats": false,
    "attributesTop": {},
    "equipmentTypes": {
      "gear": "Gear"
    },
    "moveTypes": {
      "basic": "Basic"
    }
  },
  "vehicle": {
    "label": "Vehicle",
    "baseType": "npc",
    "attributes": {
      "condition1": {
        "type": "Text",
        "label": "Condition",
        "position": "left"
      },
      "condition2": {
        "type": "Text",
        "label": "",
        "position": "left"
      },
      "condition3": {
        "type": "Text",
        "label": "",
        "position": "left"
      }
    },
    "moveTypes": {
      "basic": "Basic"
    },
    "equipmentTypes": {
      "cargo": "Cargo"
    }
  },
  "location": {
    "label": "Location",
    "baseType": "npc",
    "attributes": {
      "description": {
        "type": "LongText",
        "label": "Description",
        "position": "top"
      }
    },
    "moveTypes": {
      "events": "Location Events"
    },
    "equipmentTypes": {
      "resources": "Resources"
    }
  },
  "organization": {
    "label": "Organization",
    "baseType": "character",
    "stats": {
      "influence": "Influence",
      "resources": "Resources"
    },
    "attributes": {
      "reputation": {
        "type": "Number",
        "label": "Reputation",
        "position": "top"
      },
      "agenda": {
        "type": "LongText",
        "label": "Hidden Agenda",
        "position": "left",
        "limited": true
      }
    },
    "moveTypes": {
      "political": "Political Moves",
      "covert": "Covert Operations"
    },
    "equipmentTypes": {
      "assets": "Assets"
    }
  }
};

Hooks.once("pbtaSheetConfig", () => {
  game.settings.set("pbta", "sheetConfigOverride", true);
  game.pbta.sheetConfig = game.pbta.utils.convertSheetConfig(RAW_SHEET_CONFIG);
});
