#!/usr/bin/env python3
"""Generate the PbtA sheet override module from the authoritative TOML config."""
from pathlib import Path
import json
import tomllib

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "config" / "sheet-config.toml"
TARGET = ROOT / "scripts" / "sheet-config.js"
raw = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
content = """// Generated from config/sheet-config.toml by tools/build-sheet-config.py.\n// Do not edit this file directly.\nconst RAW_SHEET_CONFIG = %s;\n\nHooks.once(\"pbtaSheetConfig\", () => {\n  game.settings.set(\"pbta\", \"sheetConfigOverride\", true);\n  game.pbta.sheetConfig = game.pbta.utils.convertSheetConfig(RAW_SHEET_CONFIG);\n});\n""" % json.dumps(raw, indent=2, ensure_ascii=False)
TARGET.write_text(content, encoding="utf-8")
